# Generated by Django 2.2.5 on 2020-05-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=50)),
                ('activity_periods', models.CharField(max_length=50)),
            ],
        ),
    ]
